// Code generated by protoc-gen-micro
// source: service.proto
package service

import (
	context "context"
	proto "github.com/unistack-org/micro-logger-service/v3/proto"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewLoggerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

type LoggerClient interface {
	Log(ctx context.Context, req *proto.Message, opts ...client.CallOption) (*proto.Empty, error)
}

type LoggerServer interface {
	Log(ctx context.Context, req *proto.Message, rsp *proto.Empty) error
}
