// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.0.0
// - protoc              v3.21.12
// source: service.proto

package servicepb

import (
	context "context"
	proto "go.unistack.org/micro-logger-service/v3/proto"
	v4 "go.unistack.org/micro-server-http/v4"
	client "go.unistack.org/micro/v4/client"
)

var (
	LoggerServiceName = "LoggerService"
)
var (
	LoggerServiceServerEndpoints = []v4.EndpointMetadata{}
)

type LoggerServiceClient interface {
	Log(ctx context.Context, req *proto.LogReq, opts ...client.CallOption) (*proto.LogRsp, error)
}

type LoggerServiceServer interface {
	Log(ctx context.Context, req *proto.LogReq, rsp *proto.LogRsp) error
}
